require:
 - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.6
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - "tmp/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "db/migrate/*"
    - "bin/rails"
    - "bin/rake"
    - "bin/setup"
    - "bin/update"
    - "bin/spring"
    - "bin/yarn"
    - "config/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: always

Style/FormatStringToken:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/ClassLength:
  Max: 100
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Max: 25
  Exclude:
    - "spec/**/*"
    - "lib/tasks/*"

Style/Documentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false
